export interface QuestionPack {
  id: string;
  name: string;
  description: string;
  questions: string[];
}

export const PACKS: QuestionPack[] = [
  {
    id: "sfw",
    name: "Party Mode",
    description: "Clean fun for everyone",
    questions: [
      "forget their own birthday",
      "survive a zombie apocalypse",
      "accidentally become famous",
      "get lost in their own neighborhood",
      "win a hot dog eating contest",
      "become a millionaire by accident",
      "trip on a flat surface",
      "cry during a Disney movie",
      "talk their way out of a speeding ticket",
      "fall asleep during their own wedding",
      "befriend a wild animal",
      "start a book club that gets way too intense",
      "go viral on the internet for something embarrassing",
      "survive on a deserted island the longest",
      "accidentally set something on fire",
      "get into a fight with a toddler and lose",
      "become president of a small country",
      "eat something off the floor",
      "sleep through an earthquake",
      "show up to the wrong wedding and stay",
      "laugh at the worst possible moment",
      "get banned from a buffet",
      "send a text to the wrong person at the worst time",
      "win a reality TV show",
      "adopt 10 cats",
      "become a supervillain",
      "forget where they parked for 3 hours",
      "start a flash mob in a grocery store",
      "get escorted out of a store for something ridiculous",
      "still use a flip phone in 2030",
      "become a viral TikTok star",
      "accidentally join a marathon thinking it was a fun run",
      "adopt a pet rock and treat it like a real pet",
      "fall for the most obvious internet scam",
      "try to parallel park for 20 minutes",
      "get stuck in a baby swing at a playground",
      "bring a guitar to a party and play Wonderwall",
      "talk to plants and swear they talk back",
      "attend a funeral of someone they didn't know and give a speech",
      "become a local legend at a fast food restaurant",
      "get lost in a IKEA for a full day",
      "start a rumor about themselves for fun",
      "become a mall Santa",
      "write a strongly-worded letter to a company",
      "chase a squirrel across a park",
      "get banned from a library for being too loud",
      "wear a costume to work on a non-costume day",
      "become an influencer for the most mundane thing",
      "get caught dancing like nobody's watching when everyone was watching",
      "join a pyramid scheme and try to recruit everyone",
      "sign up for something intense without reading the fine print",
      "become famous for a terrible talent",
      "live in a treehouse as an adult",
      "start a podcast that no one listens to",
      "get stuck in a revolving door",
      "try to fight a goose and lose",
      "name their car and have full conversations with it",
      "get a tattoo of their favorite meme",
      "become the mayor of a small town on Foursquare",
      "end up as the face of a meme without knowing",
      "ride a unicycle to work every day",
      "get banned from a theme park for life",
      "start a collection of something weird",
      "pretend to be a tourist in their own city",
      "get caught talking to themselves on a hot mic",
      "become a competitive eater",
      "get stranded on a desert island with a volleyball",
      "get asked to fix everyone's Wi-Fi at family gatherings",
      "hold a world record for something completely pointless",
      "become obsessed with a weird hobby no one understands",
      "spend an hour getting ready just to go to the grocery store",
      "forget to wear shoes to an important meeting",
      "befriend their mail carrier and invite them to dinner",
      "perform a magic trick that goes horribly wrong",
      "get lost in their own house",
      "become the world's worst DIYer",
      "talk their way into a VIP area they don't belong in",
      "join the wrong Zoom meeting and participate for an hour",
      "show up to a costume party in regular clothes",
      "become famous for a viral kitchen fail",
      "get in a heated debate about pineapple on pizza",
      "return something they bought 5 years ago with a straight face",
      "become a hoarder of something useless",
      "sit on a whoopee cushion and blame it on someone else",
      "break every phone they've ever owned",
      "become a local news legend for a weird reason",
      "take a shortcut that adds 45 minutes to the trip",
      "accidentally order 100 of something instead of 1",
      "become obsessed with a reality TV show",
      "own a pet that's smarter than them",
      "give themselves a haircut and immediately regret it",
      "become the person who always burns popcorn",
      "walk face-first into a glass door in front of a crowd",
      "have the most embarrassing autocorrect fails",
      "become a magnet for bird poop",
      "sneeze so loud in a quiet library that everyone stares",
      "accidentally reply-all to a company-wide email",
      "become known for their terrible puns",
      "challenge a stranger to an arm wrestle",
      "attempt a backflip at a party and land on their face",
      "clear a karaoke bar with their singing",
      "wear two different shoes and not notice until noon",
      "have the worst sense of direction in the world",
      "somehow win every raffle they enter",
      "get too close to a wild animal for a photo",
      "get recognized for something they didn't do",
      "become a professional cheese tester",
      "donate their favorite thing and realize a week later",
      "have the most awkward job interview stories",
      "become the person who always spoils movie endings",
      "build IKEA furniture without the instructions and have parts left over",
      "accidentally call their teacher or boss 'mom' or 'dad'",
      "become famous for their weird sneeze",
      "forget to mute themselves on a call and say something embarrassing",
      "set off the smoke alarm making toast",
      "sing the wrong lyrics confidently for years",
      "send a meme to a serious group chat at the worst moment",
      "have the worst poker face in history",
      "become a unicyclist in a parade",
      "post a Pinterest fail and have it go viral",
      "buy something they already own three of",
      "fall asleep at a concert in the front row",
      "wave back at someone who was waving at the person behind them",
      "have the most dramatic reaction to a bee",
      "get way too competitive during a board game",
      "walk into a pole while trying to look cool",
      "delete all their photos trying to free up storage",
      "tell the same story three times in one dinner without realizing",
      "get into a screaming match with a vending machine",
      "flood their house doing a DIY plumbing job",
      "become a collector of vintage lunchboxes",
      "sit on a wet bench and walk around like that all day",
      "get hiccups during a job interview",
      "get way too emotional watching a commercial",
      "pull a push door for way too long before reading the sign",
      "return from vacation with the worst tan lines",
      "bring a full pillow and blanket to a long flight",
      "accidentally congratulate someone on their pregnancy when they're not",
      "get splashed by a car driving through a puddle",
      "wave goodbye to someone walking the same direction as them",
      "wear sunglasses indoors and walk straight into a wall",
      "walk into a screen door at a party",
      "refuse to ask for directions no matter what",
      "like a photo from 5 years ago while scrolling at 2am",
      "have the most contagious laugh",
      "sneeze with their eyes open and terrify everyone",
      "get launched off a treadmill at the gym",
      "start clapping at the wrong time during a performance",
      "insist on paying the bill and then realize they have no money",
      "send a voice message of them singing to the wrong chat",
      "leave a note that nobody can decipher",
      "tell a story that goes absolutely nowhere",
      "hide behind a cereal box to avoid someone at the store",
      "get caught singing in the car at a red light",
      "bring way too many bags to the airport",
      "end up in the wrong city because they got on the wrong bus",
      "spit out their drink laughing at the worst time",
      "wear a fanny pack unironically",
      "wink at someone and just blink both eyes instead",
      "become a competitive napper",
      "reply to bad news with a thumbs up emoji",
      "set off a car alarm in a parking lot and panic",
      "become the person who always double-dips chips",
      "storm off dramatically and walk into a closet",
      "forget why they walked into a room constantly",
      "take a selfie at the most inappropriate moment",
      "wave at their own reflection in a window",
      "say 'you too' when a waiter says 'enjoy your meal'",
      "mispronounce a common word for their entire life",
      "get caught staring at someone and pretend to look at something else",
      "trip over nothing and blame the ground",
      "eat an entire cake in one sitting and deny it",
      "call someone by their pet's name with full confidence",
      "tell a joke and be the only one who laughs",
      "laugh so hard they snort in a quiet room",
      "fake a phone call and have their phone actually ring",
      "get fooled by an obvious April Fools prank",
      "talk in their sleep and say something hilarious",
      "sit in gum and not realize until someone points it out",
      "dramatically gasp when someone cuts them in line",
      "ask for ketchup at a fancy restaurant",
      "furiously type gibberish when their boss walks by",
      "get scared by their own reflection",
      "show up overdressed to a casual hangout",
      "send a screenshot of the conversation to the person they're talking about",
      "step in something mysterious and spend all day wondering what it was",
      "become the person who always microwaves fish at work",
      "look at their watch and immediately forget what time it said",
      "fall asleep on a stranger's shoulder on the bus",
      "pocket-dial someone during an embarrassing moment",
      "run into someone they were just talking about",
      "get caught having a full conversation with a pet",
      "photobomb a stranger's family photo and end up framed on their wall",
      "mistake a mannequin for a real person and apologize to it",
      "become a competitive hula hooper",
      "lock themselves out of the house in their pajamas",
      "get into an argument with a GPS and lose",
      "buy something from an infomercial at 3am",
      "trip going up the stairs in front of a crowd",
      "wave enthusiastically at the wrong person",
      "claim to be fluent in a language and get called on it",
      "get chased by a dog on a jog",
      "fling food across the table while telling a story",
      "haggle at a store that clearly doesn't haggle",
      "show up a day early to an event and refuse to leave",
      "become the neighborhood gossip",
      "get stuck in an elevator and panic immediately",
      "hold a door open for someone who's way too far away",
      "eat someone else's clearly labeled lunch from the fridge",
      "confidently give wrong directions to a tourist",
      "get outsmarted by a child in an argument",
      "panic-buy 40 rolls of toilet paper",
      "use the wrong end of a binoculars and not realize it",
      "clap when the plane lands",
      "bring a suitcase-sized bag of snacks to a movie theater",
      "get emotionally attached to a Roomba",
      "lose a staring contest to a cat",
      "dramatically read a grocery list like it's Shakespeare",
    ],
  },
  {
    id: "nsfw",
    name: "After Dark",
    description: "Adults only, no filter",
    questions: [
      "hook up with their boss",
      "get caught watching something embarrassing",
      "send a spicy text to the wrong person",
      "get kicked out of a bar for being too rowdy",
      "wake up in a stranger's bed with no memory",
      "accidentally flash someone in public",
      "have a one night stand and forget their name",
      "get drunk and confess their deepest secret",
      "skinny dip in a public fountain",
      "date two people at the same time",
      "get caught doing the walk of shame",
      "drunk-text their ex at 3am",
      "start a fight at a party over nothing",
      "throw up on someone during a date",
      "get banned from a strip club",
      "lose their clothes on a night out",
      "wake up with a tattoo they don't remember getting",
      "pass out in someone's front yard",
      "get caught talking dirty to themselves",
      "make out with a stranger for a free drink",
      "get blackout drunk at a work event",
      "accidentally like an ex's photo from 3 years ago at 2am",
      "have the most embarrassing browser history",
      "be the loudest person in bed",
      "ghost someone after a great date",
      "get caught with their browser history on a projector",
      "hook up with a friend's sibling",
      "send nudes to their boss instead of their partner",
      "get caught faking an orgasm",
      "date someone purely for their looks",
      "have a secret affair with a coworker",
      "get caught watching their neighbor through the window",
      "sleep with someone just to get back at their ex",
      "lie about their body count",
      "get caught with a dating profile while in a relationship",
      "have a pregnancy scare from a one night stand",
      "get caught with someone's underwear in their bag",
      "send a sext meant for their partner to their parent",
      "have a crush on their best friend's partner",
      "get caught in a compromising position at work",
      "hook up with someone twice their age",
      "get banned from a hotel for being too loud",
      "have a secret OnlyFans account",
      "get caught with sex toys in their carry-on at airport security",
      "cheat on a partner and get away with it for years",
      "have a friends-with-benefits situation go wrong",
      "get caught stalking their ex on social media",
      "sleep with someone they met at a funeral",
      "have a threesome and regret it immediately",
      "get caught having sex in a public place",
      "send unsolicited pictures to someone",
      "have a secret sugar daddy/mommy",
      "get caught roleplaying something weird",
      "have sex with their roommate and make it awkward",
      "get drunk and make out with their cousin at a wedding",
      "have a weird fetish they hide from everyone",
      "get caught with a hidden camera",
      "sleep with someone just for a place to stay",
      "get caught with a fake dating profile to catfish someone",
      "have an STD and not tell their partner",
      "get caught with someone else's partner",
      "have a secret affair with their teacher or boss",
      "get caught with a dating app on their phone while married",
      "have a one night stand with a complete stranger at a party",
    ],
  },
  {
    id: "dev",
    name: "Software Engineers",
    description: "For the technically inclined",
    questions: [
      "push directly to main on a Friday at 5pm",
      "write code with zero comments and call it 'self-documenting'",
      "mass-reject pull requests for missing semicolons",
      "spend 6 hours debugging only to find a typo",
      "deploy to production without testing",
      "rewrite the entire codebase in Rust 'for fun'",
      "have 200 open browser tabs of Stack Overflow",
      "accidentally drop the production database",
      "use Comic Sans in their IDE",
      "write a 500-line function and call it clean",
      "argue about tabs vs spaces for 3 hours",
      "automate a 5-minute task with a 3-week script",
      "claim 'it works on my machine' with a straight face",
      "name their variables a, b, c, aa, bb, cc",
      "mass-commit with the message 'fixed stuff'",
      "use AI to write their entire PR and pretend they did it",
      "fall asleep during a standup meeting",
      "have a mass-meltdown over a merge conflict",
      "build their own framework instead of using an existing one",
      "have the most unread Slack messages",
      "accidentally expose API keys on GitHub",
      "refuse to use any library they didn't write themselves",
      "mass-quit after a failed deployment",
      "write unit tests after the deadline",
      "use a 10-year-old version of Node.js in production",
      "have the most chaotic .vimrc / .bashrc",
      "mass-refactor code the night before a release",
      "add a TODO comment and never come back to it",
      "mass-over-engineer a simple CRUD app",
      "mass-delete a branch someone was still using",
      "write a 10,000 line config file",
      "install 500 npm packages for a hello world app",
      "spend 8 hours choosing a color scheme for their IDE",
      "have a rubber duck they're overly attached to",
      "forget to save their work for 3 hours straight",
      "use console.log instead of a proper debugger forever",
      "accidentally commit their .env file to git",
      "have the most convoluted git history known to man",
      "write a custom regex that crashes production",
      "spend days optimizing code that doesn't need optimizing",
      "refuse to use any IDE other than Notepad",
      "have 47 different side projects and finish none",
      "write documentation that makes things more confusing",
      "create a microservice architecture for a personal blog",
      "spend more time on their dotfiles than actual coding",
      "have a keyboard with 200 custom macros they forgot",
      "write a compiler for a language no one will use",
      "argue that PHP is actually good unironically",
      "have the most broken local development environment",
      "write code that only works on their machine due to magic",
      "refuse to write tests and wonder why bugs exist",
      "use vim without knowing how to exit",
      "deploy on Friday and actually survive",
      "have the most tabs open in their browser history",
      "write a 500-line bash script instead of using Python",
      "be the reason their company has a 'no deploy Friday' policy",
      "use light theme in a dark room at 2am",
      "have git commits that say 'WIP' for months",
      "write code that's 90% comments explaining the other 10%",
      "accidentally delete production with a single command",
      "have the most chaotic folder structure known to humanity",
      "spend a week learning a framework just to abandon it",
      "write recursive functions with no base case",
      "have a stack overflow profile with only questions",
      "write a whole app in a single file with 10,000 lines",
      "use `eval()` in production code and think it's fine",
      "have more aliases than actual commands in their shell",
      "write database queries with SQL injection vulnerabilities",
      "refuse to use version control and email zip files instead",
      "hardcode API keys and passwords directly in source code",
      "have a README that's just 'it works don't touch it'",
      "write a custom JavaScript framework 'for learning'",
      "use global variables for everything and call it efficient",
      "have the most unread emails in their inbox",
      "spend hours customizing their terminal to look cool",
      "write code that works but they have no idea why",
    ],
  },
];

export function getQuestions(packIds: string[]): string[] {
  const selected = PACKS.filter((p) => packIds.includes(p.id));
  if (selected.length === 0) {
    return PACKS[0].questions;
  }
  // Merge and deduplicate
  const all = selected.flatMap((p) => p.questions);
  return [...new Set(all)];
}
